In [1]:
import pandas as pd

In [2]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print("MySQL connected successfully!")

MySQL connected successfully!

1.
List all movies in the Action genre released after 2015, showing title and release date.
JOIN (movies ⋈ movie_genres ⋈ genres)

In [ ]:
import sqlite3
import pandas as pd

# 1. Create an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')

# 2. Load CSV files into pandas DataFrames and push them to SQLite tables
pd.read_csv('movies_cleaned.csv').to_sql('movies', conn, index=False, if_exists='replace')
pd.read_csv('genres_cleaned.csv').to_sql('genres', conn, index=False, if_exists='replace')
pd.read_csv('movie_genres_cleaned.csv').to_sql('movie_genres', conn, index=False, if_exists='replace')

query_1 = """
SELECT 
    m.title,
    m.release_date
FROM movies m
JOIN movie_genres mg ON m.movie_id = mg.movie_id
JOIN genres g ON mg.genre_id = g.genre_id
WHERE g.genre_name = 'Action'
  AND CAST(SUBSTR(m.release_date, 1, 4) AS INTEGER) > 2015
ORDER BY m.release_date DESC;
"""

df_action_2015 = pd.read_sql_query(query_1, conn)
print(df_action_2015.head())

                          title release_date
0              Mortal Kombat II   2026-05-06
1            Predator: Badlands   2025-11-05
2  The Fantastic 4: First Steps   2025-07-23
3                      Superman   2025-07-09
4                            F1   2025-06-25

2.
Find the top 10 highest-grossing movies along with the genre(s) each belongs to.
JOIN + ORDER BY + LIMIT

In [6]:
query_q2 = """
SELECT 
    m.title,
    m.revenue,
    GROUP_CONCAT(g.genre_name SEPARATOR ', ') AS genres
FROM movies m
JOIN movie_genres mg 
    ON m.movie_id = mg.movie_id
JOIN genres g 
    ON mg.genre_id = g.genre_id
GROUP BY m.movie_id, m.title, m.revenue
ORDER BY m.revenue DESC LIMIT 10;"""

df_q2 = pd.read_sql_query(text(query_q2),con=engine)
df_q2

,title,revenue,genres
0,Avatar,2.923706e+09,"Action, Science Fiction, Adventure"
1,Avengers: Endgame,2.799439e+09,"Science Fiction, Adventure, Action"
2,Avatar: The Way of Water,2.334485e+09,"Action, Adventure, Science Fiction"
3,Titanic,2.264162e+09,"Drama, Romance"
4,Star Wars: The Force Awakens,2.068224e+09,"Action, Adventure, Science Fiction"
5,Avengers: Infinity War,2.052415e+09,"Science Fiction, Adventure, Action"
6,Spider-Man: No Way Home,1.921207e+09,"Adventure, Action, Science Fiction"
7,Zootopia 2,1.868209e+09,"Animation, Adventure, Comedy, Mystery, Family"
8,Inside Out 2,1.698864e+09,"Adventure, Family, Animation, Comedy"
9,Jurassic World,1.671537e+09,"Thriller, Science Fiction, Adventure"

3.
Calculate the average budget and average revenue for each genre, sorted by average revenue descending.
JOIN + GROUP BY + AVG()

In [13]:
query_q3 = """
SELECT
    g.genre_name,
    AVG(m.budget) AS average_budget,
    AVG(m.revenue) AS average_revenue
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
GROUP BY g.genre_name
ORDER BY average_revenue DESC;"""

df_q3 = pd.read_sql_query(text(query_q3),con=engine)
df_q3

         genre_name  average_budget  average_revenue
0         Adventure    1.093600e+08     3.902145e+08
1         Animation    8.336061e+07     3.597435e+08
2            Family    8.458426e+07     3.430968e+08
3   Science Fiction    9.525992e+07     3.235601e+08
4            Action    9.329457e+07     3.000547e+08
5           Fantasy    8.617784e+07     2.942975e+08
6            Comedy    5.256907e+07     2.113513e+08
7             Music    4.106939e+07     1.974526e+08
8           Romance    3.461113e+07     1.627896e+08
9          Thriller    4.938770e+07     1.605152e+08
10              War    5.332041e+07     1.563214e+08
11            Crime    4.456106e+07     1.448649e+08
12          History    5.257679e+07     1.404552e+08
13          Mystery    3.690394e+07     1.386307e+08
14            Drama    3.774313e+07     1.365055e+08
15          Western    5.236970e+07     1.348412e+08
16           Horror    2.517932e+07     1.098258e+08
17         Tv Movie    2.800000e+06     9.365000e+02
18      Documentary    0.000000e+00     0.000000e+00

4.
List the top 10 actors who have appeared in the most movies in the dataset.(cast)
GROUP BY + COUNT()

In [14]:
query_q4 = """
SELECT 
    actor_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM cast
GROUP BY person_id, actor_name
ORDER BY movie_count DESC
LIMIT 10;"""

df_q4 = pd.read_sql_query(text(query_q4),con=engine)
df_q4

           actor_name  movie_count
0   Samuel L. Jackson           39
1           Brad Pitt           38
2      Robert De Niro           38
3         Johnny Depp           37
4           Tom Hanks           33
5  Scarlett Johansson           32
6       Mark Wahlberg           32
7        Willem Dafoe           32
8          Tom Cruise           31
9      Morgan Freeman           31

5.
Find all directors who have directed more than 3 movies, along with their movie count.
GROUP BY + HAVING

In [15]:
query_q5 = """
SELECT
    person_name AS director_name,
    COUNT(movie_id) AS movie_count
FROM crew
WHERE job = 'Director'
GROUP BY person_name
HAVING COUNT(movie_id) > 3
ORDER BY movie_count DESC;
"""

df_q5 = pd.read_sql_query(text(query_q5),con=engine)
df_q5

        director_name  movie_count
0    Steven Spielberg           27
1        Ridley Scott           19
2          Tim Burton           19
3     Martin Scorsese           16
4     Robert Zemeckis           15
..                ...          ...
212      Brian Taylor            4
213    Mark Neveldine            4
214   Charlie Chaplin            4
215      Guy Hamilton            4
216     Alexandre Aja            4

[217 rows x 2 columns]

6.
List the top 10 most frequently used keywords across all movies.
GROUP BY + COUNT()

In [16]:
query_q6 = """
SELECT
    keyword_name,
    COUNT(movie_id) AS movie_count
FROM movie_keywords
GROUP BY keyword_name
ORDER BY movie_count DESC
LIMIT 10;
"""

df_q6 = pd.read_sql_query(text(query_q6),con=engine)
df_q6

             keyword_name  movie_count
0  based on novel or book          449
1                  sequel          416
2    duringcreditsstinger          296
3     aftercreditsstinger          242
4                  murder          176
5     based on true story          166
6           new york city          161
7                 villain          160
8            3d animation          155
9          based on comic          154

7.
Find movies where the budget was above the overall average budget but the revenue was below the overall average revenue.
Subquery comparison against AVG()

In [17]:
query_q7 = """
SELECT
    movie_id,
    title,
    budget,
    revenue
FROM movies
WHERE budget > (SELECT AVG(budget) FROM movies)
  AND revenue < (SELECT AVG(revenue) FROM movies)
"""

df_q7 = pd.read_sql_query(text(query_q7),con=engine)
df_q7

     movie_id                        title        budget       revenue
0         550                   Fight Club  6.300000e+07  1.008538e+08
1      228150                         Fury  6.800000e+07  2.118179e+08
2        1949                       Zodiac  6.500000e+07  8.478591e+07
3      508442                         Soul  1.500000e+08  1.219775e+08
4         197                   Braveheart  7.200000e+07  2.132162e+08
..        ...                          ...           ...           ...
312     71880                Jack and Jill  7.900000e+07  1.497000e+08
313      2642             Two Weeks Notice  6.000000e+07  1.990432e+08
314    629176                    Samaritan  1.000000e+08  7.500000e+07
315    967847  Ghostbusters: Frozen Empire  1.000000e+08  2.019675e+08
316   1368167                   Date Night  9.321480e+07  8.759568e+07

[317 rows x 4 columns]

8
List all actors who have appeared in a movie directed by a specific director (e.g., Christopher Nolan).
JOIN (cast ⋈ crew )

In [18]:
query_q8 = """
SELECT DISTINCT ca.actor_name
FROM cast ca
JOIN crew cr ON ca.movie_id = cr.movie_id
WHERE cr.person_name = 'Christopher Nolan'
  AND cr.job = 'Director'
ORDER BY ca.actor_name;"""

df_q8 = pd.read_sql_query(
    text(query_q8),
    con=engine
)

df_q8

           actor_name
0       Aaron Eckhart
1           Al Pacino
2      Alon Aboutboul
3         Andy Serkis
4     Aneurin Barnard
..                ...
79          Tom Hardy
80      Tom Wilkinson
81       Topher Grace
82        Wes Bentley
83  Yuri Kolokolnikov

[84 rows x 1 columns]

9
Find the genre with the highest average rating, considering only genres with at least 20 movies.
JOIN + GROUP BY + HAVING + AVG()

In [19]:
query_q9 = """
SELECT 
    g.genre_name,
    ROUND(AVG(m.vote_average), 2) AS avg_rating,
    COUNT(m.movie_id) AS movie_count
FROM movies m
JOIN movie_genres mg ON m.movie_id = mg.movie_id
JOIN genres g ON mg.genre_id = g.genre_id
GROUP BY g.genre_id, g.genre_name
HAVING COUNT(m.movie_id) >= 20
ORDER BY avg_rating DESC
LIMIT 1;
"""

df_q9 = pd.read_sql_query(text(query_q9),con=engine)
df_q9

  genre_name  avg_rating  movie_count
0        War        7.36           85

9
Find the genre with the highest average rating, considering only genres with at least 20 movies.
JOIN + GROUP BY + HAVING + AVG()

In [20]:
query_q9 = """
SELECT g.genre_name, AVG(m.vote_average) AS avg_rating, COUNT(m.movie_id) AS movie_count
FROM movies m
JOIN movie_genres mg ON m.movie_id = mg.movie_id
JOIN genres g ON mg.genre_id = g.genre_id
GROUP BY g.genre_name
HAVING COUNT(m.movie_id) >= 20
ORDER BY avg_rating DESC
LIMIT 1;

"""

df_q9 = pd.read_sql_query(text(query_q9),con=engine)
df_q9

  genre_name  avg_rating  movie_count
0        War    7.357576           85

10
List the top 10 movies with the highest number of keywords tagged to them. 
JOIN + GROUP BY

In [21]:
query_q10 = """
SELECT 
    m.title, 
    COUNT(mk.keyword_id) AS keyword_count
FROM movies m
JOIN movie_keywords mk ON m.movie_id = mk.movie_id
GROUP BY m.movie_id, m.title
ORDER BY keyword_count DESC
LIMIT 10;
"""
df_q10 = pd.read_sql_query(text(query_q10),con=engine)
df_q10

                                        title  keyword_count
0                                     Smile 2             98
1                                     Taken 3             70
2                                 Silent Hill             63
3                              Twelve Monkeys             57
4              War for the Planet of the Apes             54
5                                 The Shining             52
6              Dawn of the Planet of the Apes             51
7                    How to Train Your Dragon             50
8  How to Train Your Dragon: The Hidden World             49
9                       Pacific Rim: Uprising             49