In [2]:
import pandas as pd

In [3]:
# 1. Load crew and reference dataset
df_crew = pd.read_csv('crew.csv')
df_movies = pd.read_csv('movies_cleaned.csv')

In [4]:
df_crew

,crew_row_id,movie_id,person_id,person_name,job,department
0,1,157336,527,Jonathan Nolan,Writer,Writing
1,2,157336,525,Christopher Nolan,Writer,Writing
2,3,157336,525,Christopher Nolan,Director,Directing
3,4,27205,525,Christopher Nolan,Writer,Writing
4,5,27205,525,Christopher Nolan,Director,Directing
...,...,...,...,...,...,...
7292,1026,566525,57264,David Callaham,Screenplay,Writing
7293,1243,76492,53684,Robert Smigel,Screenplay,Writing
7294,5532,9352,57407,David Mandel,Writer,Writing
7295,5235,58224,89027,Jared Stern,Screenplay,Writing
7296,264,808,12083,Joe Stillman,Writer,Writing

In [8]:
df_crew.head()

   crew_row_id  movie_id  person_id        person_name       job department
0            1    157336        527     Jonathan Nolan    Writer    Writing
1            2    157336        525  Christopher Nolan    Writer    Writing
2            3    157336        525  Christopher Nolan  Director  Directing
3            4     27205        525  Christopher Nolan    Writer    Writing
4            5     27205        525  Christopher Nolan  Director  Directing

In [9]:
df_crew.tail()

      crew_row_id  movie_id  person_id     person_name         job department
7292         1026    566525      57264  David Callaham  Screenplay    Writing
7293         1243     76492      53684   Robert Smigel  Screenplay    Writing
7294         5532      9352      57407    David Mandel      Writer    Writing
7295         5235     58224      89027     Jared Stern  Screenplay    Writing
7296          264       808      12083    Joe Stillman      Writer    Writing

In [5]:
df_crew.columns

Index(['crew_row_id', 'movie_id', 'person_id', 'person_name', 'job',
       'department'],
      dtype='str')

In [6]:
df_crew.shape

(7297, 6)

In [11]:
df_crew.info()

<class 'pandas.DataFrame'>
RangeIndex: 7297 entries, 0 to 7296
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   crew_row_id  7297 non-null   int64
 1   movie_id     7297 non-null   int64
 2   person_id    7297 non-null   int64
 3   person_name  7297 non-null   str
 4   job          7297 non-null   str
 5   department   7297 non-null   str
dtypes: int64(3), str(3)
memory usage: 552.0 KB

In [16]:
# 2. clean text columns
text_cols = ['person_name', 'job', 'department']
for col in text_cols:
    df_crew[col] = df_crew[col].astype(str).str.strip()

In [17]:
#check duplicate rows
print("Duplicate rows:", df_crew.duplicated().sum())

Duplicate rows: 8

In [20]:
# 3. Drop duplicate records
df_crew_clean = df_crew.drop_duplicates(keep='first').copy()

In [21]:
df_crew_clean

,crew_row_id,movie_id,person_id,person_name,job,department
0,1,157336,527,Jonathan Nolan,Writer,Writing
1,2,157336,525,Christopher Nolan,Writer,Writing
2,3,157336,525,Christopher Nolan,Director,Directing
3,4,27205,525,Christopher Nolan,Writer,Writing
4,5,27205,525,Christopher Nolan,Director,Directing
...,...,...,...,...,...,...
7284,7285,7461,52680,Barry Levy,Writer,Writing
7285,7286,19901,56501,Michael Spierig,Director,Directing
7286,7287,19901,56502,Peter Spierig,Director,Directing
7287,7288,19901,56501,Michael Spierig,Screenplay,Writing
7288,7289,19901,56502,Peter Spierig,Screenplay,Writing

In [23]:
df_crew_clean.shape

(7289, 6)

In [24]:
# 4. Filter for valid movie_ids
valid_movies = set(df_movies['movie_id'])
df_crew_clean = df_crew_clean[df_crew_clean['movie_id'].isin(valid_movies)]

In [25]:
# 5. Export cleaned CSV
df_crew_clean.to_csv('crew_cleaned.csv', index=False)

In [26]:
df_crew_clean

,crew_row_id,movie_id,person_id,person_name,job,department
0,1,157336,527,Jonathan Nolan,Writer,Writing
1,2,157336,525,Christopher Nolan,Writer,Writing
2,3,157336,525,Christopher Nolan,Director,Directing
3,4,27205,525,Christopher Nolan,Writer,Writing
4,5,27205,525,Christopher Nolan,Director,Directing
...,...,...,...,...,...,...
7284,7285,7461,52680,Barry Levy,Writer,Writing
7285,7286,19901,56501,Michael Spierig,Director,Directing
7286,7287,19901,56502,Peter Spierig,Director,Directing
7287,7288,19901,56501,Michael Spierig,Screenplay,Writing
7288,7289,19901,56502,Peter Spierig,Screenplay,Writing

In [27]:
from sqlalchemy import create_engine
engine= create_engine(
    "mysql+pymysql://root:root@localhost/movies"
)

print("Engine created successfully!")

Engine created successfully!

In [28]:
df_crew_clean.to_sql(
     'crew',
    if_exists='replace',
    con=engine,
    index=False)

7289